name: sudoku_classic
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  flex_color_scheme: ^6.1.2
  shared_preferences: ^2.1.0
  easy_splash_screen: ^1.0.4
  

  # flutter_native_splash: ^2.2.19


  # level_map: ^0.2.0
  # game_level_map: ^1.0.0+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/

