name: sudoku_classic
version: 1.0.1+2
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  flex_color_scheme: ^6.1.2
  shared_preferences: ^2.1.0
  easy_splash_screen: ^1.0.4
  lottie: ^2.3.2
  material_dialogs: ^1.1.4
  google_mobile_ads: ^2.4.0
  connectivity_plus: ^3.0.4
  table_calendar: ^3.0.9
  # flutter_calendar_carousel: ^2.4.2




flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon_round.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon_round.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon_round.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon_round.png"
dev_dependencies:
  flutter_launcher_icons: "^0.12.0"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/animation/

